# Generated by Django 5.1.2 on 2024-10-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollaBand_App', '0003_project_creationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprojectrole',
            old_name='user',
            new_name='userID',
        ),
        migrations.RemoveField(
            model_name='userprojectrole',
            name='permissions',
        ),
        migrations.AddField(
            model_name='userprojectrole',
            name='projectID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='CollaBand_App.project'),
            preserve_default=False,
        ),
    ]
