# Generated by Django 5.1.2 on 2024-10-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollaBand_App', '0004_rename_user_userprojectrole_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
