# Generated by Django 5.1.2 on 2024-10-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollaBand_App', '0006_alter_userprojectrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectrole',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('collaborator', 'Collaborator'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
